project_id = "fnebftywudiyjguzrofg"

[functions.generate-copy]
verify_jwt = false

[functions.send-workspace-invite]
verify_jwt = false

[functions.optimize-copy]
verify_jwt = true

[functions.analyze-audience]
verify_jwt = false

[functions.setup-new-user]
verify_jwt = false

[functions.webhook-ticto]
verify_jwt = false