project_id = "fnebftywudiyjguzrofg"

[functions.generate-copy]
verify_jwt = false

[functions.generate-system-prompt]
verify_jwt = true

[functions.send-workspace-invite]
verify_jwt = false

[functions.optimize-copy]
verify_jwt = true

[functions.analyze-audience]
verify_jwt = false

[functions.setup-new-user]
verify_jwt = false

[functions.webhook-ticto]
verify_jwt = false

[functions.get-user-prompt]
verify_jwt = true

[functions.save-user-prompt]
verify_jwt = true

[functions.restore-default-prompt]
verify_jwt = true

[functions.copy-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.activate-workspace-payment]
verify_jwt = false